langauge: python
python:
  - "2.7"
sudo: required
before_install:
  - sudo apt-get install -y build-essential gfortran gcc libatlas-base-dev 
  - sudo apt-get install -y python-dev libpq-dev libssl-dev 
  - sudo apt-get install -y postgresql-client libxml2-dev
  - sudo apt-get install -y libgraphviz-dev libopenblas-dev liblapack-dev
  - sudo apt-get build-dep --fix-missing python-matplotlib
install: "sudo pip install -r requirements.txt"
script: make test_systems
