langauge: python
python:
  - "2.7"
before_install:
  - sudo apt-get install -y build-essential gfortran gcc libatlas-base-dev 
  - sudo apt-get install -y python-dev libpq-dev libssl-dev 
  - sudo apt-get install -y postgresql-client libxml2-dev libxsltl-dev 
  - sudo apt-get install -ylibgraphviz-dev libopenblas-dev liblapack-dev
install: "pip install --user -r requirements.txt"
script: make test_systems
