addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - time
    - build-essential
    - gcc-4.8
    - g++-4.8
    - gfortran
    - libatlas-dev
    - libpq-dev
    - libssl-dev
    - postgresql-client
    - libxml2-dev
    - libgraphviz-dev
    - libopenblas-dev
    - liblapack-dev
    - python-dev
    - python-setuptools
    - python-matplotlib
    - python-scipy
langauge: python
python:
  - "2.7"
install: "pip install --user -r requirements.txt"
script: make test_systems
before_install:
  - pip install --user codecov
after_success:
  - codecov --token=6d19e4ee-a03c-40a7-93cf-853cbd42f4ca
