addons:
  apt:
    packages:
      - cmake
      - time
      - build-essential
      - gcc-4.8
      - g++-4.8
      - gfortran
      - libatlas-dev
      - libatlas-dev-base
      - libatlas3gf-base
      - python-dev 
      - python-setuptools
      - python-numpy
      - python-scipy
      - libpq-dev
      - libssl-dev
      - postgresql-client
      - libxml2-dev
      - libgraphviz-dev
      - libopenblas-dev
      - liblapack-dev
langauge: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: make test_systems
