# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20160108_1903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchange',
            unique_together=set([('name',)]),
        ),
    ]
