# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20160108_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprice',
            options={'ordering': ('price_date', 'symbol')},
        ),
        migrations.RenameField(
            model_name='dailyprice',
            old_name='date_vendor',
            new_name='data_vendor',
        ),
    ]
