# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20160119_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='utc_offset',
        ),
        migrations.AlterUniqueTogether(
            name='dailyprice',
            unique_together=set([('symbol', 'price_date')]),
        ),
    ]
