# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160108_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ('name', 'ticker')},
        ),
    ]
