# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20160119_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='data_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', related_query_name='daily_price', to='data.DataVendor'),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', related_query_name='daily_price', to='data.Symbol'),
        ),
    ]
