# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-09 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20160709_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='action',
            field=models.IntegerField(choices=[(-1, 'Buy'), (1, 'Sell')], default=-1),
        ),
    ]
